version: "3.8"
services: 
    catalogdb: 
        image: mongo
    basketdb:
        image: redis
    discountdb:
        image: postgres
    orderdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
    rabbitmq:
        image: rabbitmq:3.8.17-management
    identitydb:        
         image: mcr.microsoft.com/mssql/server:2019-latest
    catalog.api:
        image: catalog_api_image
        build: 
            context: .
            dockerfile: Services/Catalog/Course.Services.Catalog/Dockerfile
    identityserver.api:
        image: identityserver_api_image
        build: 
            context: .
            dockerfile: IdentityServer/Course.IdentityServer/Dockerfile     
    basket.api:
        image: basket_api_image
        build: 
            context: .
            dockerfile: Services/Basket/Course.Services.Basket/Dockerfile   
volumes: 
    catalogdb_volume:
    discountdb_volume:
    identitydb_volume:
    orderdb_volume:    

